devel_mode.config:
  type: mapping
  label: 'Settings for devel mode'
  mapping:
    twig_debug:
      type: boolean
      label: 'Enable twig debugging'
    twig_auto_load:
      type: boolean
      label: 'Enable twig auto_load'
